name: 'Update NodeJS Test Matrix'
description: 'Update a test matrix'
inputs:
  versions:
    description: 'Versions alias to update to'
    required: true
    default: 'lts_active'
  workflowFile:
    description: 'Path to the workflow file'
    required: true
    default: '.github/workflows/test.yml'
runs:
  using: 'node12'
  main: 'index.js'
