name: "Run JavaScript Action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm it
    - name: Run with "lts"
      uses: ./
      with:
        versions: lts
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Run with "current, lts_latest"
      uses: ./
      with:
        versions: current, lts_latest
        workflowFile: .github/workflows/tmp-test.tml
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
